version: '3.8'

services:
  app:
    build: .
    container_name: simple-blog-app
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=helloworld
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: simple-blog-db
    environment:
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: simple-blog-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
